/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedReposRouteImport } from './routes/_authenticated/repos'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedIdentitiesRouteImport } from './routes/_authenticated/identities'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions/index'
import { Route as AuthenticatedReposIndexRouteImport } from './routes/_authenticated/repos/index'
import { Route as AuthenticatedSettingsReposRouteImport } from './routes/_authenticated/settings/repos'
import { Route as AuthenticatedSettingsIdentitiesRouteImport } from './routes/_authenticated/settings/identities'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions/$sessionId'
import { Route as AuthenticatedReposRepoIdRouteImport } from './routes/_authenticated/repos/$repoId'
import { Route as AuthenticatedSettingsReposIndexRouteImport } from './routes/_authenticated/settings/repos.index'
import { Route as AuthenticatedSessionsSessionIdIndexRouteImport } from './routes/_authenticated/sessions/$sessionId.index'
import { Route as AuthenticatedSettingsReposRepoIdRouteImport } from './routes/_authenticated/settings/repos.$repoId'
import { Route as AuthenticatedSessionsSessionIdReviewRouteImport } from './routes/_authenticated/sessions/$sessionId.review'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReposRoute = AuthenticatedReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdentitiesRoute = AuthenticatedIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedReposIndexRoute = AuthenticatedReposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedReposRoute,
} as any)
const AuthenticatedSettingsReposRoute =
  AuthenticatedSettingsReposRouteImport.update({
    id: '/repos',
    path: '/repos',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIdentitiesRoute =
  AuthenticatedSettingsIdentitiesRouteImport.update({
    id: '/identities',
    path: '/identities',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedReposRepoIdRoute =
  AuthenticatedReposRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => AuthenticatedReposRoute,
  } as any)
const AuthenticatedSettingsReposIndexRoute =
  AuthenticatedSettingsReposIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsReposRoute,
  } as any)
const AuthenticatedSessionsSessionIdIndexRoute =
  AuthenticatedSessionsSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSessionsSessionIdRoute,
  } as any)
const AuthenticatedSettingsReposRepoIdRoute =
  AuthenticatedSettingsReposRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => AuthenticatedSettingsReposRoute,
  } as any)
const AuthenticatedSessionsSessionIdReviewRoute =
  AuthenticatedSessionsSessionIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/identities': typeof AuthenticatedIdentitiesRoute
  '/new': typeof AuthenticatedNewRoute
  '/repos': typeof AuthenticatedReposRouteWithChildren
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/repos/$repoId': typeof AuthenticatedReposRepoIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/settings/identities': typeof AuthenticatedSettingsIdentitiesRoute
  '/settings/repos': typeof AuthenticatedSettingsReposRouteWithChildren
  '/repos/': typeof AuthenticatedReposIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/sessions/$sessionId/review': typeof AuthenticatedSessionsSessionIdReviewRoute
  '/settings/repos/$repoId': typeof AuthenticatedSettingsReposRepoIdRoute
  '/sessions/$sessionId/': typeof AuthenticatedSessionsSessionIdIndexRoute
  '/settings/repos/': typeof AuthenticatedSettingsReposIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/identities': typeof AuthenticatedIdentitiesRoute
  '/new': typeof AuthenticatedNewRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/repos/$repoId': typeof AuthenticatedReposRepoIdRoute
  '/settings/identities': typeof AuthenticatedSettingsIdentitiesRoute
  '/repos': typeof AuthenticatedReposIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/sessions/$sessionId/review': typeof AuthenticatedSessionsSessionIdReviewRoute
  '/settings/repos/$repoId': typeof AuthenticatedSettingsReposRepoIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdIndexRoute
  '/settings/repos': typeof AuthenticatedSettingsReposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/identities': typeof AuthenticatedIdentitiesRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/repos': typeof AuthenticatedReposRouteWithChildren
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/repos/$repoId': typeof AuthenticatedReposRepoIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/_authenticated/settings/identities': typeof AuthenticatedSettingsIdentitiesRoute
  '/_authenticated/settings/repos': typeof AuthenticatedSettingsReposRouteWithChildren
  '/_authenticated/repos/': typeof AuthenticatedReposIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/sessions/$sessionId/review': typeof AuthenticatedSessionsSessionIdReviewRoute
  '/_authenticated/settings/repos/$repoId': typeof AuthenticatedSettingsReposRepoIdRoute
  '/_authenticated/sessions/$sessionId/': typeof AuthenticatedSessionsSessionIdIndexRoute
  '/_authenticated/settings/repos/': typeof AuthenticatedSettingsReposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/identities'
    | '/new'
    | '/repos'
    | '/sessions'
    | '/settings'
    | '/repos/$repoId'
    | '/sessions/$sessionId'
    | '/settings/identities'
    | '/settings/repos'
    | '/repos/'
    | '/sessions/'
    | '/sessions/$sessionId/review'
    | '/settings/repos/$repoId'
    | '/sessions/$sessionId/'
    | '/settings/repos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/identities'
    | '/new'
    | '/settings'
    | '/'
    | '/repos/$repoId'
    | '/settings/identities'
    | '/repos'
    | '/sessions'
    | '/sessions/$sessionId/review'
    | '/settings/repos/$repoId'
    | '/sessions/$sessionId'
    | '/settings/repos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/identities'
    | '/_authenticated/new'
    | '/_authenticated/repos'
    | '/_authenticated/sessions'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/repos/$repoId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/settings/identities'
    | '/_authenticated/settings/repos'
    | '/_authenticated/repos/'
    | '/_authenticated/sessions/'
    | '/_authenticated/sessions/$sessionId/review'
    | '/_authenticated/settings/repos/$repoId'
    | '/_authenticated/sessions/$sessionId/'
    | '/_authenticated/settings/repos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repos': {
      id: '/_authenticated/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AuthenticatedReposRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/identities': {
      id: '/_authenticated/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof AuthenticatedIdentitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/repos/': {
      id: '/_authenticated/repos/'
      path: '/'
      fullPath: '/repos/'
      preLoaderRoute: typeof AuthenticatedReposIndexRouteImport
      parentRoute: typeof AuthenticatedReposRoute
    }
    '/_authenticated/settings/repos': {
      id: '/_authenticated/settings/repos'
      path: '/repos'
      fullPath: '/settings/repos'
      preLoaderRoute: typeof AuthenticatedSettingsReposRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/identities': {
      id: '/_authenticated/settings/identities'
      path: '/identities'
      fullPath: '/settings/identities'
      preLoaderRoute: typeof AuthenticatedSettingsIdentitiesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/repos/$repoId': {
      id: '/_authenticated/repos/$repoId'
      path: '/$repoId'
      fullPath: '/repos/$repoId'
      preLoaderRoute: typeof AuthenticatedReposRepoIdRouteImport
      parentRoute: typeof AuthenticatedReposRoute
    }
    '/_authenticated/settings/repos/': {
      id: '/_authenticated/settings/repos/'
      path: '/'
      fullPath: '/settings/repos/'
      preLoaderRoute: typeof AuthenticatedSettingsReposIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsReposRoute
    }
    '/_authenticated/sessions/$sessionId/': {
      id: '/_authenticated/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdIndexRouteImport
      parentRoute: typeof AuthenticatedSessionsSessionIdRoute
    }
    '/_authenticated/settings/repos/$repoId': {
      id: '/_authenticated/settings/repos/$repoId'
      path: '/$repoId'
      fullPath: '/settings/repos/$repoId'
      preLoaderRoute: typeof AuthenticatedSettingsReposRepoIdRouteImport
      parentRoute: typeof AuthenticatedSettingsReposRoute
    }
    '/_authenticated/sessions/$sessionId/review': {
      id: '/_authenticated/sessions/$sessionId/review'
      path: '/review'
      fullPath: '/sessions/$sessionId/review'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdReviewRouteImport
      parentRoute: typeof AuthenticatedSessionsSessionIdRoute
    }
  }
}

interface AuthenticatedReposRouteChildren {
  AuthenticatedReposRepoIdRoute: typeof AuthenticatedReposRepoIdRoute
  AuthenticatedReposIndexRoute: typeof AuthenticatedReposIndexRoute
}

const AuthenticatedReposRouteChildren: AuthenticatedReposRouteChildren = {
  AuthenticatedReposRepoIdRoute: AuthenticatedReposRepoIdRoute,
  AuthenticatedReposIndexRoute: AuthenticatedReposIndexRoute,
}

const AuthenticatedReposRouteWithChildren =
  AuthenticatedReposRoute._addFileChildren(AuthenticatedReposRouteChildren)

interface AuthenticatedSessionsSessionIdRouteChildren {
  AuthenticatedSessionsSessionIdReviewRoute: typeof AuthenticatedSessionsSessionIdReviewRoute
  AuthenticatedSessionsSessionIdIndexRoute: typeof AuthenticatedSessionsSessionIdIndexRoute
}

const AuthenticatedSessionsSessionIdRouteChildren: AuthenticatedSessionsSessionIdRouteChildren =
  {
    AuthenticatedSessionsSessionIdReviewRoute:
      AuthenticatedSessionsSessionIdReviewRoute,
    AuthenticatedSessionsSessionIdIndexRoute:
      AuthenticatedSessionsSessionIdIndexRoute,
  }

const AuthenticatedSessionsSessionIdRouteWithChildren =
  AuthenticatedSessionsSessionIdRoute._addFileChildren(
    AuthenticatedSessionsSessionIdRouteChildren,
  )

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRouteWithChildren
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsSessionIdRoute:
    AuthenticatedSessionsSessionIdRouteWithChildren,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedSettingsReposRouteChildren {
  AuthenticatedSettingsReposRepoIdRoute: typeof AuthenticatedSettingsReposRepoIdRoute
  AuthenticatedSettingsReposIndexRoute: typeof AuthenticatedSettingsReposIndexRoute
}

const AuthenticatedSettingsReposRouteChildren: AuthenticatedSettingsReposRouteChildren =
  {
    AuthenticatedSettingsReposRepoIdRoute:
      AuthenticatedSettingsReposRepoIdRoute,
    AuthenticatedSettingsReposIndexRoute: AuthenticatedSettingsReposIndexRoute,
  }

const AuthenticatedSettingsReposRouteWithChildren =
  AuthenticatedSettingsReposRoute._addFileChildren(
    AuthenticatedSettingsReposRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsIdentitiesRoute: typeof AuthenticatedSettingsIdentitiesRoute
  AuthenticatedSettingsReposRoute: typeof AuthenticatedSettingsReposRouteWithChildren
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsIdentitiesRoute: AuthenticatedSettingsIdentitiesRoute,
  AuthenticatedSettingsReposRoute: AuthenticatedSettingsReposRouteWithChildren,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIdentitiesRoute: typeof AuthenticatedIdentitiesRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedReposRoute: typeof AuthenticatedReposRouteWithChildren
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIdentitiesRoute: AuthenticatedIdentitiesRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedReposRoute: AuthenticatedReposRouteWithChildren,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
